---
- hosts: masters
  vars:
    kubernetes_allow_pods_on_master: true
    kubernetes_role: 'master'
    kubernetes_pod_network_cidr: '192.168.10.0/24'
    kubernetes_kubeadm_init_extra_opts: '--apiserver-advertise-address={{ ansible_host }}'
    kubernetes_kubelet_extra_args: '--node-ip={{ ansible_host }}'
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes

- hosts: nodes
  vars:
    kubernetes_role: 'node'
    kubernetes_pod_network_cidr: '192.168.10.0/24'
    kubernetes_kubelet_extra_args: '--node-ip={{ ansible_host }}'
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes
